[tool.poetry]
name = "utilitiesrobot"
version = "1.0.0"
description = ""
authors = ["Divkix <techdroidroot@gmail.com>", "Jayant Hegde Kageri <jayantkageri@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
kantex = "^0.2.0"
Telethon = "^1.25.4"
proxygrab = "^1.2.9"
aiohttp = "^3.8.3"
pdf2image = "^1.16.0"
gTTS = "^2.2.4"
tgEasy = "^1.3.3"
ujson = "^5.5.0"
Pillow = "^9.2.0"
google-trans-new = "^1.1.9"
pypers = "^1.2.7"
removebg = "^0.04"
SQLAlchemy = "^1.4.42"
redis = "^4.3.4"
pymongo = "^4.3.2"

[tool.poetry.dev-dependencies]
black = "^22.10.0"
pyclean = "^2.2.0"
pylint = "^2.15.4"
isort = "^5.10.1"
pre-commit = "^2.20.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
