[tool.poetry]
name = "minibotspython"
version = "1.5.3"
description = ""
authors = ["Divanshu Chauhan <23524935+Divkix@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.9"
asyncio = "~=3.4.3"
beautifulsoup4 = "~=4.10.0"
dnspython = "~=2.1.0"
lxml = "~=4.6.3"
proxygrab = "~=1.1.0"
pymongo = "~=3.12.0"
Pyrogram = "~=1.2.9"
telegraph = "~=2.1.0"
TgCrypto = "~=1.2.2"
Telethon = "~=1.23.0"
aiohttp = {extras = ["speedups"], version = "^3.7.4"}
pyromod = {git = "https://github.com/usernein/pyromod"}

[tool.poetry.dev-dependencies]
black = "~=21.9b0"
isort = "~=5.10.0"
pre-commit = "~=2.15.0"
pyclean = "~=2.0.0"
pylint = "~=2.12.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
