[tool.poetry]
name = "utilitiesrobot"
version = "1.0.0"
description = ""
authors = ["Divkix <techdroidroot@gmail.com>", "Jayant Hegde Kageri <jayantkageri@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
kantex = "^0.2.0"
Telethon = "^1.26.1"
proxygrab = "^1.2.9"
aiohttp = "^3.8.3"
pdf2image = "^1.16.2"
gTTS = "^2.3.1"
tgEasy = "^1.3.3"
ujson = "^5.7.0"
Pillow = "^9.4.0"
google-trans-new = "^1.1.9"
pypers = "^1.2.7"
removebg = "^0.04"
SQLAlchemy = "^2.0.1"
redis = "^4.4.2"
pymongo = "^4.3.3"

[tool.poetry.dev-dependencies]
black = "^23.1.0"
pyclean = "^2.6.0"
pylint = "^2.16.1"
isort = "^5.12.0"
pre-commit = "^3.0.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
