[tool.poetry]
name = "utilitiesrobot"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.9"
tgEasy = "^1.2.6"
kantex = "^0.2.0"
Telethon = "^1.23.0"
cryptg = "^0.2.post4"
proxygrab = "^1.1.3"
aiohttp = "^3.8.1"

[tool.poetry.dev-dependencies]
black = "^21.11b0"
pyclean = "^2.0.0"
pylint = "^2.11.1"
isort = "^5.10.1"
pre-commit = "^2.15.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
