[tool.poetry]
name = "utilitiesrobot"
version = "0.1.0"
description = ""
authors = ["Divkix <techdroidroot@gmail.com>", "Jayant Hegde Kageri <jayantkageri@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
kantex = "^0.2.0"
Telethon = "^1.24.0"
cryptg = "^0.2.post4"
proxygrab = "^1.2.2"
aiohttp = "^3.8.1"
Pillow = "^9.0.1"
pdf2image = "^1.16.0"
gTTS = "^2.2.3"
ujson = "^4.3.0"
tgeasy = {git = "https://github.com/jayantkageri/tgEasy.git", rev = "7abf9d072b2acca6db09e3c55021465b707bf73d"}

[tool.poetry.dev-dependencies]
black = "^22.1"
pyclean = "^2.0.0"
pylint = "^2.12.2"
isort = "^5.10.1"
pre-commit = "^2.17.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
