name: Release CI

on:
  push:
    branches:
      - main
    paths:
      - bots/
      - poetry.lock
      - pyproject.toml
      - Dockerfile
      - .dockerignore
      - .github/workflows/release.yml
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to release"

jobs:
  get-repo-info:
    uses: divkix/reusable-workflows/.github/workflows/get-repo-info.yml@main

  build-docker:
    needs: get-repo-info
    uses: divkix/reusable-workflows/.github/workflows/docker-build-publish.yml@main
    with:
      repo_name: ${{ needs.get-repo-info.outputs.repo_name }}
      dockerfile: ./Dockerfile
      latest_image: true
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  automerge-dependabot-pr:
    needs: build-docker
    uses: divkix/reusable-workflows/.github/workflows/automerge-dependabot-pr.yml@main
